# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'component' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYModel'
  # Pods for component

  target 'componentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'componentUITests' do
    # Pods for testing
  end

end
